### ISSUE TITLE
No unit tests for aio module

### ISSUE THREAD

**Issue by krister-ts** [ftd2xx/ftd2xx#27]
The aio module was not added to the unit tests. As it is now, both FTD2XX classes inherit from the same base class. I don't think this is too important until the aio module is substantially different.

I think we should keep this issue open as a reminder until the right PR comes along.

**Comment by krister-ts** [comment]
@snmishra Do you want to create a milestone to change the aio module to make use of the asyncio.Transport and asyncio.Protocol like pyserial-asyncio? I think that would be the time to make serious tests for aio.

**Comment by krister-ts** [comment]
UPDATE: I am working on making the asyncio.Transport!!

@snmishra

So I finally started using asyncio.Protocol at work for TCP connections using proprietary binary protocol. I've made a transport by copying from pyserial-asyncio and hacking it up a bit. It works. I just need to figure out what I've bypassed and what the equivalents for d2xx should be.

Don't be surprised if you get a PR soon. In the meantime, could you look at licensing? I don't know much about that sort of thing... Is it as simple as crediting the pyserial team for most of the code?

**Comment by krister-ts** [comment]
@snmishra Would it make sense to make this a new project? This is what pyserial-asyncio does. I hope that no one is relying on the aio module yet since it is experimental.

**Comment by krister-ts** [comment]
Maybe you could make an organization (on the free plan) called ftd2xx to keep both projects under the same umbrella.

**Comment by snmishra** [comment]
Moved mine.

**Comment by krister-ts** [comment]
> Moved mine.

I don't have permission to transfer mine yet

**Comment by snmishra** [comment]
Added you as a member, hope that works.
